[package]
name = "ecc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
lazy_static = "1.4.0"
num-bigint = "0.4.4"
num-traits = "0.2.17"
rand = "0.8.5"
secp256k1 = "0.28.0"
